name: Terraform Azure Workflow

on:
  push:
    branches:
      - main  # Déclenche le workflow sur un push vers la branche 'main'
  pull_request:
    branches:
      - main  # Déclenche le workflow lors de la création d'une PR vers la branche 'main'
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow depuis l'interface GitHub

jobs:
  terraform:
    runs-on: ubuntu-latest  # Utilise Ubuntu comme environnement de runner

    steps:
      # Étape 1 : Checkout du code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.5'  # Utilise la version Terraform que tu préfères

      # Étape 3 : Configurer les credentials Azure
      - name: Set up Azure credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Utilise le secret contenant le JSON du Service Principal
      # cat files
      - name: cat files
        run: cat main.tf
      # Étape 4 : Initialiser Terraform
      - name: Terraform Init
        run: terraform init -backend-config=
      - name: Check if terraform.tfstate exists
        run: ls -l terraform.tfstate
      - name: show state content
        run: cat terraform.tfstate
      - name: show state list
        run: terraform state list
      - name: show rg in state
        run: terraform state show azurerm_resource_group.example
      # Étape 5 : Exécuter Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Étape 6 : Appliquer Terraform (applique uniquement sur un push, pas lors des PR)
      - name: Terraform Apply
        if: github.event_name == 'push'  # Applique uniquement sur un push (pas lors des PR)
        run: terraform apply -auto-approve

       # Étape 7 : Commit tfstate 
      - name: Commit and Push terraform state
        run: |
          cat terraform.tfstate
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add terraform.tfstate
          git commit -m "Commit terraform state"
          git push origin main

